CREATE TABLE YellowTaxiData (
    doLocationId NVARCHAR(255),
    endLat FLOAT,
    endLon FLOAT,
    extra FLOAT,
    fareAmount FLOAT,
    improvementSurcharge NVARCHAR(255),
    mtaTax FLOAT,
    passengerCount INT,
    paymentType NVARCHAR(255),
    puLocationId NVARCHAR(255),
    puMonth INT,
    puYear INT,
    rateCodeId INT,
    startLat FLOAT,
    startLon FLOAT,
    storeAndFwdFlag NVARCHAR(255),
    tipAmount FLOAT,
    tollsAmount FLOAT,
    totalAmount FLOAT,
    tpepDropoffDateTime DATETIME,
    tpepPickupDateTime DATETIME,
    tripDistance FLOAT,
    vendorID NVARCHAR(255),
    vendorID_LPEP INT
);